// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ip_service.proto

package ip

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TellMeYourIPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientIp string `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
}

func (x *TellMeYourIPRequest) Reset() {
	*x = TellMeYourIPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TellMeYourIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TellMeYourIPRequest) ProtoMessage() {}

func (x *TellMeYourIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ip_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TellMeYourIPRequest.ProtoReflect.Descriptor instead.
func (*TellMeYourIPRequest) Descriptor() ([]byte, []int) {
	return file_ip_service_proto_rawDescGZIP(), []int{0}
}

func (x *TellMeYourIPRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type TellMeYourIPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerIp string `protobuf:"bytes,1,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
}

func (x *TellMeYourIPResponse) Reset() {
	*x = TellMeYourIPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TellMeYourIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TellMeYourIPResponse) ProtoMessage() {}

func (x *TellMeYourIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ip_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TellMeYourIPResponse.ProtoReflect.Descriptor instead.
func (*TellMeYourIPResponse) Descriptor() ([]byte, []int) {
	return file_ip_service_proto_rawDescGZIP(), []int{1}
}

func (x *TellMeYourIPResponse) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

var File_ip_service_proto protoreflect.FileDescriptor

var file_ip_service_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x69, 0x70, 0x22, 0x32, 0x0a, 0x13, 0x54, 0x65, 0x6c, 0x6c, 0x4d, 0x65,
	0x59, 0x6f, 0x75, 0x72, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x22, 0x33, 0x0a, 0x14, 0x54, 0x65,
	0x6c, 0x6c, 0x4d, 0x65, 0x59, 0x6f, 0x75, 0x72, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x70, 0x32,
	0x4e, 0x0a, 0x09, 0x49, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c,
	0x54, 0x65, 0x6c, 0x6c, 0x4d, 0x65, 0x59, 0x6f, 0x75, 0x72, 0x49, 0x50, 0x12, 0x17, 0x2e, 0x69,
	0x70, 0x2e, 0x54, 0x65, 0x6c, 0x6c, 0x4d, 0x65, 0x59, 0x6f, 0x75, 0x72, 0x49, 0x50, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x69, 0x70, 0x2e, 0x54, 0x65, 0x6c, 0x6c, 0x4d,
	0x65, 0x59, 0x6f, 0x75, 0x72, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x05, 0x5a, 0x03, 0x2f, 0x69, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ip_service_proto_rawDescOnce sync.Once
	file_ip_service_proto_rawDescData = file_ip_service_proto_rawDesc
)

func file_ip_service_proto_rawDescGZIP() []byte {
	file_ip_service_proto_rawDescOnce.Do(func() {
		file_ip_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ip_service_proto_rawDescData)
	})
	return file_ip_service_proto_rawDescData
}

var file_ip_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ip_service_proto_goTypes = []interface{}{
	(*TellMeYourIPRequest)(nil),  // 0: ip.TellMeYourIPRequest
	(*TellMeYourIPResponse)(nil), // 1: ip.TellMeYourIPResponse
}
var file_ip_service_proto_depIdxs = []int32{
	0, // 0: ip.IPService.TellMeYourIP:input_type -> ip.TellMeYourIPRequest
	1, // 1: ip.IPService.TellMeYourIP:output_type -> ip.TellMeYourIPResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ip_service_proto_init() }
func file_ip_service_proto_init() {
	if File_ip_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ip_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TellMeYourIPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ip_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TellMeYourIPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ip_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ip_service_proto_goTypes,
		DependencyIndexes: file_ip_service_proto_depIdxs,
		MessageInfos:      file_ip_service_proto_msgTypes,
	}.Build()
	File_ip_service_proto = out.File
	file_ip_service_proto_rawDesc = nil
	file_ip_service_proto_goTypes = nil
	file_ip_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IPServiceClient is the client API for IPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IPServiceClient interface {
	TellMeYourIP(ctx context.Context, in *TellMeYourIPRequest, opts ...grpc.CallOption) (*TellMeYourIPResponse, error)
}

type iPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPServiceClient(cc grpc.ClientConnInterface) IPServiceClient {
	return &iPServiceClient{cc}
}

func (c *iPServiceClient) TellMeYourIP(ctx context.Context, in *TellMeYourIPRequest, opts ...grpc.CallOption) (*TellMeYourIPResponse, error) {
	out := new(TellMeYourIPResponse)
	err := c.cc.Invoke(ctx, "/ip.IPService/TellMeYourIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPServiceServer is the server API for IPService service.
type IPServiceServer interface {
	TellMeYourIP(context.Context, *TellMeYourIPRequest) (*TellMeYourIPResponse, error)
}

// UnimplementedIPServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIPServiceServer struct {
}

func (*UnimplementedIPServiceServer) TellMeYourIP(context.Context, *TellMeYourIPRequest) (*TellMeYourIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TellMeYourIP not implemented")
}

func RegisterIPServiceServer(s *grpc.Server, srv IPServiceServer) {
	s.RegisterService(&_IPService_serviceDesc, srv)
}

func _IPService_TellMeYourIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TellMeYourIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).TellMeYourIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ip.IPService/TellMeYourIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).TellMeYourIP(ctx, req.(*TellMeYourIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IPService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ip.IPService",
	HandlerType: (*IPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TellMeYourIP",
			Handler:    _IPService_TellMeYourIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ip_service.proto",
}
