apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:

    exporters:
      logging:

      jaeger:
        endpoint: "simplest-collector.observability-sven.svc.cluster.local:14250"
        insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, jaeger]
