apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wallet-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallet-http
    spec:
      containers:
        - name: wallet-http
          securityContext:
            capabilities:
              add: [ "SYS_PTRACE" ]
          image: wallet-http:v1.0.32
          ports:
            - containerPort: 8112
            - containerPort: 40000
        - name: agent
          image: otel/opentelemetry-collector:0.18.0
          args:
            - --config=/conf/agent.yaml
          volumeMounts:
            - mountPath: /conf
              name: agent-config
      volumes:
        - configMap:
            items:
              - key: agent.yaml
                path: agent.yaml
            name: agent-config
          name: agent-config
