apiVersion: v1
kind: Service
metadata:
  name: wallet-http-local
spec:
  ports:
    - protocol: TCP
      port: 8119
      targetPort: 8119
---
kind: Endpoints
apiVersion: v1
metadata:
  name: wallet-http-local
subsets:
  - addresses:
      - ip: 192.168.65.2
    ports:
      - port: 8119
