apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ip-grpc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ip-grpc
    spec:
      containers:
        - name: ip-grpc
          image: ip-grpc:v1.0.11
          ports:
            - containerPort: 8113
