apiVersion: v1
kind: Service
metadata:
  name: kafka-local
spec:
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
---
kind: Endpoints
apiVersion: v1
metadata:
  name: kafka-local
subsets:
  - addresses:
      - ip: 192.168.65.2
    ports:
      - port: 9092
